"""added developer id, property type id, and added relationship for them

Revision ID: 60a388a4083f
Revises: 8d623f0aa3c9
Create Date: 2026-08-15 15:34:43.160804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a388a4083f'
down_revision = '8d623f0aa3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('property_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'developer', ['developer_id'], ['id'])
        batch_op.create_foreign_key(None, 'property_type', ['property_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('property_type_id')
        batch_op.drop_column('developer_id')

    # ### end Alembic commands ###
