"""empty message

Revision ID: 7856f3a2a18d
Revises: 52e917c88230
Create Date: 2026-09-18 18:07:17.840087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7856f3a2a18d'
down_revision = '52e917c88230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.alter_column('end_price_range',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.alter_column('end_price_range',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
