"""removed property type id and developer id

Revision ID: 8d623f0aa3c9
Revises: ca2b4b650667
Create Date: 2026-08-15 15:33:46.690207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d623f0aa3c9'
down_revision = 'ca2b4b650667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.drop_column('developer')
        batch_op.drop_column('property_type')
        batch_op.drop_column('developer_id')
        batch_op.drop_column('property_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('developer_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('property_type', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('developer', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
