"""added property listing and amenity

Revision ID: b63dbd03bd59
Revises: ea2e536277cd
Create Date: 2026-08-15 14:59:59.046547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b63dbd03bd59'
down_revision = 'ea2e536277cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_landing_page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version_landing_page',
    sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
