"""property name can be repeated

Revision ID: ca2b4b650667
Revises: b63dbd03bd59
Create Date: 2026-08-15 15:16:14.025599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2b4b650667'
down_revision = 'b63dbd03bd59'
branch_labels = None
depends_on = None

def has_index(table_name, index_name):
    """Check if an index exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        if has_index('property_listing', 'name'):
            batch_op.drop_index(batch_op.f('name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        if not has_index('property_listing', 'name'):
            batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
