"""added column for proprty type description

Revision ID: ea2e536277cd
Revises: 92c1646086b6
Create Date: 2026-08-10 15:48:02.596974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea2e536277cd'
down_revision = '92c1646086b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_type', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
